# Generated by Django 4.1.7 on 2023-02-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='uploads/'),
        ),
    ]
