# Generated by Django 4.1.7 on 2023-02-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='avatar.png', upload_to='uploads/'),
        ),
    ]
