# Generated by Django 4.1.7 on 2023-02-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Справочник доп.польз.данных', 'verbose_name_plural': 'Справочник доп.польз.данных'},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={'ordering': ['profileID'], 'verbose_name': 'Профиль', 'verbose_name_plural': '1. ПРОФИЛИ'},
        ),
        migrations.AlterModelOptions(
            name='userrights',
            options={'ordering': ['userID'], 'verbose_name': 'Права', 'verbose_name_plural': '2. ПРАВА ПОЛЬЗОВАТЕЛЕЙ'},
        ),
        migrations.AlterModelOptions(
            name='view_userset',
            options={'managed': False, 'ordering': ['subCategorySort']},
        ),
    ]
