# Generated by Django 4.1.7 on 2023-03-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_options_alter_profiles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateUsersDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=250, verbose_name='Элемент')),
                ('last_name', models.TextField(max_length=250, verbose_name='Элемент')),
                ('first_name', models.TextField(max_length=250, verbose_name='Элемент')),
                ('email', models.EmailField(max_length=250, verbose_name='Элемент')),
                ('password1', models.TextField(max_length=250, verbose_name='Элемент')),
                ('password2', models.TextField(max_length=250, verbose_name='Элемент')),
                ('is_active', models.BooleanField(max_length=250, verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Справочник пользователей',
                'verbose_name_plural': 'Справочник пользователей',
                'ordering': ['id'],
            },
        ),
    ]
