# Generated by Django 4.1.7 on 2023-03-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_updateusersdatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryTitle',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='categoryID_FK',
            field=models.ForeignKey(db_column='categoryID_FK', on_delete=django.db.models.deletion.PROTECT, related_name='categoryTitle1', to='users.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='profilesindex',
            name='profileIndexTitle',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Наименование Профиля'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subCategoryTitle',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Наименование элемента'),
        ),
    ]
