# Generated by Django 4.1.7 on 2023-03-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profiles_categoryid_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='categoryID_FK',
            field=models.ForeignKey(db_column='categoryID_FK', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='users.category', verbose_name='Категория'),
        ),
    ]
