# Generated by Django 4.1.7 on 2023-03-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profiles_categoryid_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='categoryID_FK',
            field=models.ForeignKey(db_column='categoryID_FK', on_delete=django.db.models.deletion.PROTECT, to='users.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='profileIndex_FK',
            field=models.ForeignKey(db_column='profileIndex_FK', on_delete=django.db.models.deletion.PROTECT, to='users.profilesindex', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='subCategoryID_FK',
            field=models.ForeignKey(db_column='subCategoryID_FK', on_delete=django.db.models.deletion.PROTECT, to='users.subcategory', verbose_name='Элемент категории'),
        ),
    ]
