# Generated by Django 4.1.7 on 2023-03-17 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_alter_profiles_categoryid_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrights',
            name='profilesIndex_FK',
            field=models.ForeignKey(db_column='profilesIndex_FK', on_delete=django.db.models.deletion.PROTECT, to='users.profilesindex', unique=True, verbose_name='Прикрепленный профиль'),
        ),
        migrations.AlterField(
            model_name='userrights',
            name='userID',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Пользователь'),
        ),
    ]
