# Generated by Django 4.1.7 on 2023-03-23 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_alter_userrights_profilesindex_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateUsersDataModel',
        ),
        migrations.AlterField(
            model_name='userrights',
            name='userID',
            field=models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь/Пользователем'),
        ),
    ]
